# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 它德结项瓜逗

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "0 0,13 1-7/1 3 *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  cd ~/HAOYANGMAO
                  git checkout master
                  npm install
                 
            - name: "运行 【她的节享京豆】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SYNCURL: /ta.js
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  GITHUB: ${{ secrets.GITHUB }}
                  HELPURL: ${{ secrets.HELPURL }}
